-- A key is generated by the school client for each submit attempt. PostgreSQL
-- permits multiple NULLs in a unique index, preserving compatibility with
-- historic/imported requests that predate idempotency support.
ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "idempotencyKey" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Request_schoolId_idempotencyKey_key"
  ON "Request" ("schoolId", "idempotencyKey");
